# SITE CONFIGURATION
title: TOUCHING ELEPHANT # your site title
author: mokpolar # You :P
description: > # Meta description of Homepage
  IT 입문자가 코끼리를 살펴가듯 차근 차근 공부해나가는 블로그.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mokpolar.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: mokpolar
  #links:
  #  - https://twitter.com/BenBalter
  #  - https://www.facebook.com/ben.balter
  #  - https://www.linkedin.com/in/BenBalter
  #  - https://plus.google.com/+BenBalter
  #  - https://github.com/benbalter
  #  - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - { name: "Home", link: "/" }
  - { name: "Devlog", link: "/devlog" }
  - { name: "Blog", link: "/blog" }
  - { name: "About", link: "/about" }

tagline: >
  코끼리를 살펴가듯 차근 차근 공부해나가는 블로그

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: beholder16@gmail.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username: mokpolar # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: mokpolar-github-io

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ["_pages"]
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
